# DEV environment

version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 'foley/frontend:dev'
    ports:
      - 8080:80
    environment:
      BASE_URL: http://localhost/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 'foley/backend:dev'
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongo:27017/playgrounds
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    hostname: mongo
    ports:
      - 27017:27017
