# DEV environment

version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: 'foley/frontend:dev'
    ports:
      - 80:8080
    environment:
      NODE_ENV: development
      BASE_URL: http://localhost/
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: 'foley/backend:dev'
    hostname: backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/playgrounds
      WAIT_HOSTS: mongo:27017
    volumes:
      - ./backend:/opt/app
      - /opt/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - 27017:27017
