# base image
FROM node:14-alpine

# set working directory
WORKDIR /opt/app

ENV PATH /opt/app/node_modules/.bin:$PATH

COPY entrypoint-dev.sh .
ENTRYPOINT ["sh", "./entrypoint-dev.sh"]

EXPOSE 3000

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

# start app
CMD /wait && yarn dev