name: CD
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    environment: CD
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Publish Foley Docker Frontend Image
      uses: ./.github/actions/docker
      env:
        DOCKER_BUILDKIT: 1
      with:
        # check https://github.community/t5/GitHub-Actions/Github-Actions-Docker-login/td-p/29852
        username: 'xapixbot'
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        image_name: 'xapixio/foley-frontend'
        dockerfile_path: './frontend/Dockerfile'
        build_context: './frontend'
        build_params: '--progress plain'
        #cache: true

    - name: Publish Foley Docker Frontend Image
      uses: ./.github/actions/docker
      env:
        DOCKER_BUILDKIT: 1
      with:
        # check https://github.community/t5/GitHub-Actions/Github-Actions-Docker-login/td-p/29852
        username: 'xapixbot'
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        image_name: 'xapixio/foley-backend'
        dockerfile_path: './backend/Dockerfile'
        build_context: './backend'
        build_params: '--progress plain'
        #cache: true

  deploy-neu:
    runs-on: ubuntu-latest
    environment: CD
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.XAPIXBOT_GITHUB_TOKEN}}" >> .npmrc
        working-directory: ./infra
      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:
          VERSION: ${{ github.sha }}
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_XAPIXBOT }}
          PULUMI_CI: up
          PULUMI_ROOT: infra
